#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/ama-connect/ama-connect /usr/bin/ama-connect

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/ama-connect.service ]; then
			rm /etc/systemd/system/ama-connect.service /usr/lib/systemd/system/ama-connect.service /usr/lib/systemd/user/ama-connect.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/ama-connect/files/systemd/ama-connect.service /usr/lib/systemd/system/ama-connect.service
		# try fix error in Ubuntu 18.04
		# Failed to reload ama-connect.service: Unit ama-connect.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/ama-connect.service:10: Executable path is not absolute: pkill -f "ama-connect --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/ama-connect.service
		fi
		systemctl daemon-reload
		systemctl enable ama-connect
		systemctl start ama-connect
	fi
fi
